version: "3.1"
services:
  db:
    image: mariadb:11.2
    environment:
      MARIADB_ROOT_PASSWORD: foobarhogepiyo
    volumes:
      - ex_gen_app2_data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  ex_gen_app2_data: